name: Type Checks

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  type-check:
    uses: voxpelli/ghatemplates/.github/workflows/type-check.yml@main
    with:
      ts-versions: '4.5,4.6,4.7'
      ts-libs: 'es2020;esnext'
